# Generated by Django 4.1.5 on 2024-01-09 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Beskrivelse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('str', models.TextField()),
                ('belig', models.TextField()),
                ('antal', models.IntegerField()),
                ('beskriv', models.TextField()),
                ('opred', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Dinner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('morgen', models.TextField()),
                ('middag', models.TextField()),
                ('aften', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('dato', models.DateField(blank=True, null=True)),
                ('person', models.IntegerField()),
                ('pris', models.CharField(max_length=250)),
            ],
        ),
    ]
