# Generated by Django 4.1.5 on 2024-01-11 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Oplev',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('afstand', models.TextField()),
                ('beskriv', models.TextField()),
                ('foto', models.ImageField(blank=True, upload_to='images/')),
            ],
        ),
    ]
