# Generated by Django 4.1.5 on 2024-01-14 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0002_oplev'),
    ]

    operations = [
        migrations.AddField(
            model_name='beskrivelse',
            name='pris',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
