# Generated by Django 4.1.5 on 2024-01-16 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0003_beskrivelse_pris'),
    ]

    operations = [
        migrations.AddField(
            model_name='dinner',
            name='name',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
