# Generated by Django 4.1.5 on 2024-01-18 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0004_dinner_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fejl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nr', models.IntegerField(blank=True)),
                ('fejl', models.TextField()),
                ('mangler', models.TextField()),
                ('forslag', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='beskrivelse',
            name='nr',
            field=models.IntegerField(blank=True, default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dinner',
            name='nr',
            field=models.IntegerField(blank=True, default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reservation',
            name='nr',
            field=models.IntegerField(blank=True, default=1),
            preserve_default=False,
        ),
    ]
