# Generated by Django 4.1.5 on 2024-01-21 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0006_fejl_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='rejse',
            field=models.DateField(blank=True, null=True),
        ),
    ]
