# Generated by Django 4.1.5 on 2024-02-04 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0008_reservation_kontakt'),
    ]

    operations = [
        migrations.AddField(
            model_name='beskrivelse',
            name='telt',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='telt',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='kontakt',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='pris',
            field=models.IntegerField(),
        ),
    ]
